version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    ports:
      - "8080:80"
      - "3012:3012"
    volumes:
      - /container-data/vaultwarden/vw-data/:/data/
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: xxxx
      SIGNUPS_ALLOWED: false
      LOG_FILE: /data/vaultwarden.log