version: '3'
services:
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        restart: unless-stopped
        volumes:
            - '/container-data/adguardhome/adg-work:/opt/adguardhome/work'
            - '/container-data/adguardhome/adg-conf:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
            - '3000:3000/tcp'
            - ‘853:853/tcp'
            - '853:853/udp'
            
        
