version: '3'
services:
    db:
        container_name: joplin-db
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=passord
            - POSTGRES_USER=username
            - POSTGRES_DB=joplin
    app:
        container_name: joplin-server
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_BASE_URL=https://domain:port/
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=liang
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAX_TIME_DRIFT=0